// https://nerdcave.com/tailwind-cheat-sheet
//
const colors = require('tailwindcss/colors')
const plugin = require('tailwindcss/plugin')

const em = (px) => `${px / 16}em`
const rem = (px) => ({ [px]: `${px / 16}rem` })
const px = (num) => ({ [num]: `${num}px` })

const basicColors = {
  primary: {
    DEFAULT: 'rgb(143, 105, 77)',
    light: 'rgba(122, 93, 232, 0.2)',
    pastel: '#dddaf6',
    teens: '#4c9cff',
    teensLight: '#d5ebff',
  },
  secondary: '#513ccd',
  secondary2: '#3f3d88',
  transparent: 'transparent',
  current: 'currentColor',
  gray: {
    DEFAULT: '#f9fafb',
    100: '#f2f4f6',
    200: '#e5e8eb',
    300: '#d1d6db',
    400: '#b0b8c1',
    500: '#8b95a1',
    600: '#6b7684',
    700: '#4e5968',
    800: '#333d4b',
    900: '#191f28',
  },
  grayOpacity: {
    DEFAULT: 'rgba(249, 250, 251, 0.15)',
    100: 'rgba(2,32,71,0.05)',
    200: 'rgba(0,27,55,0.1)',
    300: 'rgba(0,29,58,0.18)',
    400: 'rgba(0,29,54,0.31)',
    500: 'rgba(3,24,50,0.46)',
    600: 'rgba(0,19,43,0.58)',
    700: 'rgba(3,18,40,0.7)',
    800: 'rgba(0,12,30,0.8)',
    900: 'rgba(2,9,19,0.91)',
  },
  success: { DEFAULT: '#3cd278', light: 'rgba(60, 210, 120, 0.1)' },
  warning: { DEFAULT: '#f6c343', strong: '#FFC31C', light: 'rgb(246, 195, 67, 0.1)' },
  black: {
    DEFAULT: '#000000',
    overlay: 'rgba(0, 0, 0, 0.7)',
  },
  white: '#ffffff',
  danger: { DEFAULT: '#ff3051', light: 'rgba(255, 48, 81, 0.1)' },
  info: { DEFAULT: '#2a97ff', light: 'rgba(42, 151, 255, 0.1)' },
}

const teensColors = {
  primary: { DEFAULT: 'rgb(174, 86, 28)', light: '#dbebff' },
  secondary: '#317CD9',
  secondary2: '#105DBB',
  transparent: 'transparent',
  current: 'currentColor',
  gray: {
    DEFAULT: 'rgb(142, 142, 147)',
    100: 'rgb(242, 242, 247)',
    200: 'rgb(209, 209, 214)',
    300: 'rgb(174, 174, 178)',
    400: 'rgb(142, 142, 147)',
    500: 'rgb(99, 99, 102)',
    600: 'rgb(58, 58, 60)',
    700: 'rgb(28, 28, 30)',
  },
  success: { DEFAULT: '#3ACABB', light: '#d8f4f1' },
  warning: { DEFAULT: '#F6D34A', light: '#f5edd0'},
  black: {
    DEFAULT: '#1b1b1b',
    overlay: 'rgba(0, 0, 0, 0.7)',
  },
  white: '#ffffff',
  danger: { DEFAULT: '#FA5C5C', light: '#FFD2D2' },
  info: { DEFAULT: '#B774EC', light: '#F5E5FF' },
}

module.exports = {
  content: [
    "src/pages/**/*.{js,ts,jsx,tsx}",
    "src/components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // 'sm:text-d3',
    {
      pattern: /text-d(1|2|3|4|5|6|7|8|9)/,
      variants: ['sm', 'md', 'lg', 'xld', 'xl', 'smd', 'mdd', 'lgd'],
    },
  ],
  mode: 'jit',
  theme: {
    screensPrefix:{
      smd: '',
      sm: '',
      mdd:'',
      md: '',
      lgd:'',
      lg: '',
      xld:'',
      xl: '',
    },
    screens: {
      smd: { 
        max: em(639) 
      },
      sm: em(640),
      mdd: { max: em(719) },
      md: em(720),
      lgd: { max: em(1039) },
      lg: em(1040),
      xld: { max: em(1279) },
      xl: em(1280),
    },

    // 2021 DESIGN SYSTEM
    colors: process.env.CONF_IS_TEENS == 'true' ? teensColors : basicColors,
    fontFamily: {
      sans: ['Noto Sans KR', 'sans-serif'], //.font-sans
      serif: ['Droid serif', 'Georgia', 'serif'], //.font-serif
      nanum: ['Nanum Myeongjo', 'sans-serif'], //.font-nanum
    },
    fontSize: {
      // .text-dN
      d1: ['60px', { lineHeight: '84px' }, { letterSpacing: '-1.5px' }],
      d2: ['52px', { lineHeight: '72px' }, { letterSpacing: '-1px' }],
      d3: ['40px', { lineHeight: '56px' }, { letterSpacing: '-1px' }],
      d4: ['32px', { lineHeight: '50px' }],
      d5: ['24px', { lineHeight: '32px' }],
      d6: ['20px', { lineHeight: '32px' }],
      d7: ['18px', { lineHeight: '28px' }],
      d8: ['16px', { lineHeight: '24px' }],
      // H tags(.text-hN)
      h1: ['24px', { lineHeight: '36px' }, { fontWeight: 'bold' }],
      h2: ['20px', { lineHeight: '30px' }, { fontWeight: 'bold' }],
      h3: ['18px', { lineHeight: '27px' }, { fontWeight: 'medium' }], //h3 ====> medium
      h4: ['16px', { lineHeight: '24px' }, { fontWeight: 'bold' }],
      h5: ['14px', { lineHeight: '21px' }, { fontWeight: 'bold' }],
      h6: ['12px', { lineHeight: '18px' }, { fontWeight: 'bold' }],
      sTitle: ['16px', { lineHeight: '24px' }],
      sBody: ['14px', { lineHeight: '21px' }],

      //numeric labeling
      ...rem(9),
      ...rem(10),
      ...rem(11),
      ...rem(12),
      ...rem(13),
      ...rem(14),
      ...rem(16),
      ...rem(18),
      ...rem(20),
      ...rem(22),
      ...rem(24),
      ...rem(26),
      ...rem(28),
      ...rem(30),
      ...rem(32),
      ...rem(34),
      ...rem(36),
      ...rem(38),
      ...rem(40),
      ...rem(42),
      lg: ['16px', { lineHeight: '20px' }],
      md: ['14px', { lineHeight: '21px' }],
      sm: ['12px', { lineHeight: '20px' }],
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.03em',
      normal: '0em',
      wide: '0.03em',
      wider: '0.05em',
      widest: '0.1em',
    },
    truncate: {
      lines: {
        2: '2',
        3: '3',
        4: '4',
        5: '5',
      },
    },
    extend: {
      // numeric numbering
      spacing: {
        ...rem(1),
        ...rem(2),
        ...rem(3),
        ...rem(4),
        ...rem(5),
        ...rem(6),
        ...rem(7),
        ...rem(8),
        ...rem(9),
        ...rem(10),
        ...rem(11),
        ...rem(12),
        ...rem(14),
        ...rem(16),
        ...rem(18),
        ...rem(20),
        ...rem(24),
        ...rem(28),
        ...rem(32),
        ...rem(36),
        ...rem(40),
        ...rem(42),
        ...rem(44),
        ...rem(46),
        ...rem(48),
        ...rem(56),
        ...rem(64),
        ...rem(72),
        ...rem(80),
        ...rem(84),
        ...rem(88),
        ...rem(96),
        ...rem(104),
        ...rem(108),
        ...rem(112),
        ...rem(120),
        ...rem(128),
        ...rem(140),
        ...rem(150),
        ...rem(160),
        ...rem(167),
        ...rem(170),
        ...rem(180),
        ...rem(190),
        ...rem(200),
        ...rem(210),
        ...rem(220),
        ...rem(230),
        ...rem(240),
        ...rem(250),
        ...rem(260),
        ...rem(270),
        ...rem(280),
        ...rem(290),
        ...rem(358),
        ...rem(416),
        ...rem(1040),

        a: '4px',
        b: '8px',
        c: '12px',
        d: '16px',
        e: '24px',
        f: '28px',
        g: '40px',
        h: '48px',
        i: '64px',
        j: '80px',
        k: '96px',
        l: '104px',
        m: '112px',
        n: '128px',
        o: '280px',
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.3125rem',
        lg: '10px',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      borderWidth: {
        ...px(1),
        ...px(2),
        ...px(3),
        ...px(4),
        ...px(5),
        ...px(8),
      },
      boxShadow: {
        sm: '0 2px 10px -2px rgba(67, 86, 100, 0.1)',
        DEFAULT:
          '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        none: 'none',
      },
      letterSpacing: {
        tight: '-0.025em',
        tighter: '-0.05em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      lineHeight: {
        none: '1',
        tight: '1.25',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
        3: '.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.6em',
        7: '1.8em',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
      },
      listStyleType: {
        none: 'none',
        disc: 'disc',
        decimal: 'decimal',
      },
      maxWidth: (theme, { breakpoints }) => ({
        ...rem(1040),
        '3xl': '45rem',
        '4xl': '60rem',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        ...breakpoints(theme('screens')),
      }),
      zIndex: {
        '-10': '-10',
        0: 0,
        10: 10,
        20: 20,
        30: 30,
        40: 40,
        50: 50,
        60: 60,
        70: 70,
        80: 80,
        90: 90,
        100: 100,
        110: 110,
        120: 120,
        130: 130,
        140: 140,
        150: 150,
        160: 160,
        170: 170,
        180: 180,
        190: 190,
        200: 200,
        210: 210,
        220: 220,
        230: 230,
        240: 240,
        250: 250,
        260: 260,
        270: 270,
        280: 280,
        290: 290,
        300: 300,
        3000: 3000,
        3010: 3010,
        3020: 3020,
        3030: 3030,
        9999: 9999,
        auto: 'auto',
      },
    },
  },
  plugins: [
    // https://tailwind-bootstrap-grid.netlify.app/
    require('tailwind-bootstrap-grid')(), //container > row > col
    require('tailwindcss-truncate-multiline')(['responsive', 'hover']),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
    require('tailwind-safelist-generator')({
      patterns: [
        'text-{colors}',
        'border-{borderWidth}',
        '{screensPrefix}:gap-{gap}',
        'text-{fontSize}',

        'border-r',
        '{screensPrefix}:border-r',

        '{screensPrefix}:text-{spacing}',

        'pl-{spacing}',
        'pr-{spacing}',
        'pt-{spacing}',
        'pb-{spacing}',
        'px-{spacing}',
        'py-{spacing}',
        '{screensPrefix}:pl-{spacing}',
        '{screensPrefix}:pr-{spacing}',
        '{screensPrefix}:pt-{spacing}',
        '{screensPrefix}:pb-{spacing}',
        '{screensPrefix}:px-{spacing}',
        '{screensPrefix}:py-{spacing}',

        'ml-{spacing}',
        'mr-{spacing}',
        'mt-{spacing}',
        'mb-{spacing}',
        'mx-{spacing}',
        'my-{spacing}',
        '{screensPrefix}:ml-{spacing}',
        '{screensPrefix}:mr-{spacing}',
        '{screensPrefix}:mt-{spacing}',
        '{screensPrefix}:mb-{spacing}',
        '{screensPrefix}:mx-{spacing}',
        '{screensPrefix}:my-{spacing}',

        'translate-x-{spacing}',
        'translate-y-{spacing}',

        'justify-between',
        'justify-center',
        'justify-start',
        'justify-end',
        'justify-around',
        'justify-evenly',
        '{screensPrefix}:justify-between',
        '{screensPrefix}:justify-center',
        '{screensPrefix}:justify-start',
        '{screensPrefix}:justify-end',
        '{screensPrefix}:justify-around',
        '{screensPrefix}:justify-evenly',

        'items-start',
        'items-stretch',
        'items-center',
        'items-end',
        'items-baseline',
        '{screensPrefix}:items-start',
        '{screensPrefix}:items-stretch',
        '{screensPrefix}:items-center',
        '{screensPrefix}:items-end',
        '{screensPrefix}:items-baseline',

        'justify-center',
        '{screensPrefix}:justify-around',

        'text-left',
        'text-center',
        'text-right',
        '{screensPrefix}:text-left',
        '{screensPrefix}:text-center',
        '{screensPrefix}:text-right',

        'row',
        '{screensPrefix}:row',
        '{screensPrefix}:flex-row',

        'col-1',
        'col-2',
        'col-3',
        'col-4',
        'col-5',
        'col-6',
        'col-7',
        'col-8',
        'col-9',
        'col-10',
        'col-11',
        'col-12',
        'col-auto',
        'col',
        '{screensPrefix}:col',
        '{screensPrefix}:col-1',
        '{screensPrefix}:col-2',
        '{screensPrefix}:col-3',
        '{screensPrefix}:col-4',
        '{screensPrefix}:col-5',
        '{screensPrefix}:col-6',
        '{screensPrefix}:col-7',
        '{screensPrefix}:col-8',
        '{screensPrefix}:col-9',
        '{screensPrefix}:col-10',
        '{screensPrefix}:col-11',
        '{screensPrefix}:col-12',
        '{screensPrefix}:flex-col',
        //
        //
        //
        //

        'no-gutters',
        'container',
        'boxBorder',
        'boxContent',
        'hidden',
        'block',
        'inline-block',
        'inline',
        'inline-flex',
        'table',
        'table-caption',
        'table-column',
        'table-cell',
        'table-column-group',
        'table-footer-group',
        'table-header-group',
        'table-row-group',
        'table-row',
        'flow-root',
        'grid',
        'inline-grid',
        'contents',
        'float-right',
        'float-left',
        'float-none',
        'clear-left',
        'clear-right',
        'clear-both',
        'clear-none',
        'object-contain',
        'object-cover',
        'object-fill',
        'object-none',
        'object-scale-down',
        'object-bottom',
        'object-center',
        'object-left',
        'object-left-bottom',
        'object-left-top',
        'object-right',
        'object-right-bottom',
        'object-right-top',
        'object-top',
        'overflow-auto',
        'overflow-hidden',
        'overflow-visible',
        'overflow-scroll',
        'overflow-x-auto',
        'overflow-y-auto',
        'overflow-x-hidden',
        'overflow-y-hidden',
        'overflow-x-visible',
        'overflow-y-visible',
        'overflow-x-scroll',
        'overflow-y-scroll',
        'overscroll-auto',
        'overscroll-contain',
        'overscroll-none',
        'overscroll-y-auto',
        'overscroll-y-contain',
        'overscroll-y-none',
        'overscroll-x-auto',
        'overscroll-x-contain',
        'overscroll-x-none',
        'static',
        'fixed',
        'absolute',
        'relative',
        'sticky',
        'visible',
        'invisible',
        'z-0',
        'z-10',
        'z-20',
        'z-30',
        'z-40',
        'z-50',
        'z-auto',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-7',
        'grid-cols-8',
        'grid-cols-9',
        'grid-cols-10',
        'grid-cols-11',
        'grid-cols-12',
        'grid-cols-none',
        'col',
        'col-auto',
        'col-end-1',
        'col-end-2',
        'col-end-3',
        'col-end-4',
        'col-end-5',
        'col-end-6',
        'col-end-7',
        'col-end-8',
        'col-end-9',
        'col-end-10',
        'col-end-11',
        'col-end-12',
        'col-end-13',
        'col-end-auto',
        'col-span-1',
        'col-span-2',
        'col-span-3',
        'col-span-4',
        'col-span-5',
        'col-span-6',
        'col-span-7',
        'col-span-8',
        'col-span-9',
        'col-span-10',
        'col-span-11',
        'col-span-12',
        'col-span-full',
        'col-start-1',
        'col-start-2',
        'col-start-3',
        'col-start-4',
        'col-start-5',
        'col-start-6',
        'col-start-7',
        'col-start-8',
        'col-start-9',
        'col-start-10',
        'col-start-11',
        'col-start-12',
        'col-start-13',
        'col-start-auto',
        'grid-rows-1',
        'grid-rows-2',
        'grid-rows-3',
        'grid-rows-4',
        'grid-rows-5',
        'grid-rows-6',
        'grid-rows-none',
        'row',
        'row-auto',
        'row-span-1',
        'row-span-2',
        'row-span-3',
        'row-span-4',
        'row-span-5',
        'row-span-6',
        'row-span-full',
        'row-start-1',
        'row-start-2',
        'row-start-3',
        'row-start-4',
        'row-start-5',
        'row-start-6',
        'row-start-7',
        'row-start-auto',
        'row-end-1',
        'row-end-2',
        'row-end-3',
        'row-end-4',
        'row-end-5',
        'row-end-6',
        'row-end-7',
        'row-end-auto',
        'grid-flow-row',
        'grid-flow-col',
        'grid-flow-row-dense',
        'grid-flow-col-dense',
        'auto-cols-auto',
        'auto-cols-min',
        'auto-cols-max',
        'auto-cols-fr',
        'auto-rows-auto',
        'auto-rows-min',
        'auto-rows-max',
        'auto-rows-fr',
        'm-auto',
        'my-auto',
        'mx-auto',
        'mr-auto',
        'ml-auto',
        'text-d1',
        'text-d2',
        'text-d3',
        'text-d4',
        'text-d5',
        'text-d6',
        'text-d1',
        'text-d2',
        'text-d3',
        'text-d4',
        'text-d5',
        'text-d6',
        'text-d7',
        'text-h1',
        'text-h2',
        'text-h3',
        'text-h4',
        'text-h5',
        'text-h6',
        'text-sBody',
        'text-sTitle',
        'text-h1',
        'text-h2',
        'text-h3',
        'text-h4',
        'text-h5',
        'text-h6',
        'text-transparent',
        'text-current',
        'text-black',
        'text-white',
        'text-info',
        'text-danger',
        'text-warning',
        'text-success',
        'text-primary',
        'text-secondary',
        'text-secondary2',
        'text-gray-100',
        'text-gray-200',
        'text-gray-300',
        'text-gray-400',
        'text-gray-500',
        'text-gray-600',
        'text-gray-700',
        'text-opacity-0',
        'text-opacity-5',
        'text-opacity-10',
        'text-opacity-20',
        'text-opacity-25',
        'text-opacity-30',
        'text-opacity-40',
        'text-opacity-50',
        'text-opacity-60',
        'text-opacity-70',
        'text-opacity-75',
        'text-opacity-80',
        'text-xs',
        'text-sm',
        'text-base',
        'text-lg',
        'text-xl',
        'antialiased',
        'subpixel-antialiased',
        'italic',
        'not-italic',
        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-bold',
        'font-extrabold',
        'font-black',
        'normal-nums',
        'ordinal',
        'slashed-zero',
        'lining-nums',
        'oldstyle-nums',
        'proportional-nums',
        'tabular-nums',
        'diagonal-fractions',
        'stack-fractions',
        'tracking-tighter',
        'tracking-tight',
        'tracking-normal',
        'tracking-wide',
        'tracking-wider',
        'tracking-widest',
        'leading-none',
        'leading-tight',
        'leading-snug',
        'leading-normal',
        'leading-relaxed',
        'leading-loose',
        'leading-3',
        'leading-4',
        'leading-5',
        'leading-6',
        'leading-7',
        'leading-8',
        'leading-9',
        'leading-10',
        'list-none',
        'list-disc',
        'list-decimal',
        'list-inside',
        'list-outside',
        'placeholder-transparent',
        'placeholder-current',
        'placeholder-black',
        'placeholder-white',
        'placeholder-primary',
        'placeholder-info',
        'placeholder-danger',
        'placeholder-warning',
        'placeholder-success',
        'placeholder-gray-100',
        'placeholder-gray-200',
        'placeholder-gray-300',
        'placeholder-gray-400',
        'placeholder-gray-500',
        'placeholder-gray-600',
        'placeholder-gray-700',
        'placeholder-opacity-0',
        'placeholder-opacity-5',
        'placeholder-opacity-10',
        'placeholder-opacity-20',
        'placeholder-opacity-25',
        'placeholder-opacity-30',
        'placeholder-opacity-40',
        'placeholder-opacity-50',
        'placeholder-opacity-60',
        'placeholder-opacity-70',
        'placeholder-opacity-75',
        'placeholder-opacity-80',
        'placeholder-opacity-90',
        'placeholder-opacity-95',
        'placeholder-opacity-100',
        'text-left',
        'text-center',
        'text-right',
        'text-justify',
        'underline',
        'line-through',
        'no-underline',
        'uppercase',
        'lowercase',
        'capitalize',
        'normal-case',
        'truncate',
        'overflow-ellipsis',
        'overflow-clip',
        'align-baseline',
        'align-top',
        'align-middle',
        'align-bottom',
        'align-text-top',
        'align-text-bottom',
        'whitespace-normal',
        'whitespace-nowrap',
        'whitespace-pre',
        'whitespace-pre-line',
        'whitespace-pre-wrap',
        'break-normal',
        'break-words',
        'break-all',
        'keep-all',
        'rounded-none',
        'rounded-sm',
        'rounded',
        'rounded-md',
        'rounded-lg',
        'rounded-xl',
        'rounded-2xl',
        'rounded-3xl',
        'rounded-full',
        'rounded-t-none',
        'rounded-r-none',
        'rounded-b-none',
        'rounded-l-none',
        'rounded-t-sm',
        'rounded-r-sm',
        'rounded-b-sm',
        'rounded-l-sm',
        'rounded-t',
        'rounded-r',
        'rounded-b',
        'rounded-l',
        'rounded-t-md',
        'rounded-r-md',
        'rounded-b-md',
        'rounded-l-md',
        'rounded-t-lg',
        'rounded-r-lg',
        'rounded-b-lg',
        'rounded-l-lg',
        'rounded-t-xl',
        'rounded-r-xl',
        'rounded-b-xl',
        'rounded-l-xl',
        'rounded-t-2xl',
        'rounded-r-2xl',
        'rounded-b-2xl',
        'rounded-l-2xl',
        'rounded-t-3xl',
        'rounded-r-3xl',
        'rounded-b-3xl',
        'rounded-l-3xl',
        'rounded-t-full',
        'rounded-r-full',
        'rounded-b-full',
        'rounded-l-full',
        'rounded-tl-none',
        'rounded-tr-none',
        'rounded-br-none',
        'rounded-bl-none',
        'rounded-tl-sm',
        'rounded-tr-sm',
        'rounded-br-sm',
        'rounded-bl-sm',
        'rounded-tl',
        'rounded-tr',
        'rounded-br',
        'rounded-bl',
        'rounded-tl-md',
        'rounded-tr-md',
        'rounded-br-md',
        'rounded-bl-md',
        'rounded-tl-lg',
        'rounded-tr-lg',
        'rounded-br-lg',
        'rounded-bl-lg',
        'rounded-tl-xl',
        'rounded-tr-xl',
        'rounded-br-xl',
        'rounded-bl-xl',
        'rounded-tl-2xl',
        'rounded-tr-2xl',
        'rounded-br-2xl',
        'rounded-bl-2xl',
        'rounded-tl-3xl',
        'rounded-tr-3xl',
        'rounded-br-3xl',
        'rounded-bl-3xl',
        'rounded-tl-full',
        'rounded-tr-full',
        'rounded-br-full',
        'rounded-bl-full',
        'border',
        'border0',
        'border-1',
        'border-2',
        'border-3',
        'border-4',
        'border-8',
        'border-t',
        'border-t-0',
        'border-t-1',
        'border-t-2',
        'border-t-3',
        'border-t-4',
        'border-t-8',
        'border-r',
        'border-r-0',
        'border-r-1',
        'border-r-2',
        'border-r-3',
        'border-r-4',
        'border-r-8',
        'border-b',
        'border-b-0',
        'border-b-1',
        'border-b-2',
        'border-b-3',
        'border-b-4',
        'border-b-8',
        'border-l',
        'border-l-0',
        'border-l-1',
        'border-l-2',
        'border-l-3',
        'border-l-4',
        'border-l-8',
        'border-transparent',
        'border-current',
        'border-black',
        'border-white',
        'border-primary',
        'border-info',
        'border-danger',
        'border-warning',
        'border-success',
        'border-secondary2',
        'border-gray-100',
        'border-gray-200',
        'border-gray-300',
        'border-gray-400',
        'border-gray-500',
        'border-gray-600',
        'border-gray-700',
        'border-opacity-0',
        'border-opacity-5',
        'border-opacity-10',
        'border-opacity-25',
        'border-opacity-30',
        'border-opacity-40',
        'border-opacity-50',
        'border-opacity-60',
        'border-opacity-70',
        'border-opacity-75',
        'border-opacity-80',
        'border-opacity-90',
        'border-opacity-95',
        'border-opacity-100',
        'border-solid',
        'border-dashed',
        'border-dotted',
        'border-double',
        'border-none',
        'ring-0',
        'ring-1',
        'ring-2',
        'ring-4',
        'ring-8',
        'ring',
        'ring-inset',
        'ring-transparent',
        'ring-current',
        'ring-black',
        'ring-white',
        'ring-primary',
        'ring-info',
        'ring-danger',
        'ring-warning',
        'ring-success',
        'ring-gray-100',
        'ring-gray-200',
        'ring-gray-300',
        'ring-gray-400',
        'ring-gray-500',
        'ring-gray-600',
        'ring-gray-700',
        'ring-opacity-0',
        'ring-opacity-5',
        'ring-opacity-10',
        'ring-opacity-20',
        'ring-opacity-25',
        'ring-opacity-30',
        'ring-opacity-40',
        'ring-opacity-50',
        'ring-opacity-60',
        'ring-opacity-70',
        'ring-opacity-75',
        'ring-opacity-80',
        'ring-opacity-90',
        'ring-opacity-95',
        'ring-opacity-100',
        'ring-offset-0',
        'ring-offset-1',
        'ring-offset-2',
        'ring-offset-4',
        'ring-offset-8',
        'ring-offset-transparent',
        'ring-offset-current',
        'ring-offset-black',
        'ring-offset-white',
        'ring-offset-primary',
        'ring-offset-info',
        'ring-offset-danger',
        'ring-offset-warning',
        'ring-offset-success',
        'ring-offset-gray-100',
        'ring-offset-gray-200',
        'ring-offset-gray-300',
        'ring-offset-gray-400',
        'ring-offset-gray-500',
        'ring-offset-gray-600',
        'ring-offset-gray-700',
        'border-collapse',
        'border-separate',
        'table-auto',
        'table-fixed',
        'rotate-0',
        'rotate-1',
        'rotate-2',
        'rotate-3',
        'rotate-6',
        'rotate-12',
        'rotate-45',
        'rotate-90',
        'rotate-180',
        '-rotate-180',
        '-rotate-90',
        '-rotate-45',
        '-rotate-12',
        '-rotate-6',
        '-rotate-3',
        '-rotate-2',
        '-rotate-1',
        'translate-x-0',
        'translate-x-1/2',
        'translate-x-full',
        '-translate-x-1/2',
        '-translate-x-full',
        'translate-y-0',
        'translate-y-1/2',
        'translate-y-full',
        '-translate-y-1/2',
        '-translate-y-full',
        'transform',
        'transform-gpu',
        'transform-none',
        'shadow-sm',
        'shadow',
        'shadow-md',
        'shadow-lg',
        'shadow-xl',
        'shadow-2xl',
        'shadow-inner',
        'shadow-none ',
        'opacity-0',
        'opacity-5',
        'opacity-10',
        'opacity-20',
        'opacity-25',
        'opacity-30',
        'opacity-40',
        'opacity-50',
        'opacity-60',
        'opacity-70',
        'opacity-75',
        'opacity-80',
        'opacity-90',
        'opacity-95',
        'opacity-100',
        'fill-current',
        'stroke-current',
        'stroke-0',
        'stroke-1',
        'stroke-2',
        'flex',
        'flex-row',
        'flex-row-reverse',
        'flex-col',
        'flex-col-reverse',
        'flex-wrap',
        'flex-wrap-reverse',
        'flex-nowrap',
        'flex-1',
        'flex-auto',
        'flex-initial',
        'flex-none',
        'flex-grow',
        'flex-grow-0',
        'flex-shrink',
        'flex-shrink-0',
        'order-first',
        'order-last',
        'order-none',
        'order-1',
        'order-2',
        'order-3',
        'order-4',
        'order-5',
        'order-6',
        'order-7',
        'order-8',
        'order-9',
        'order-10',
        'order-11',
        'order-12',
        'justify-start',
        'justify-end',
        'justify-center',
        'justify-between',
        'justify-around',
        'justify-evenly',
        'justify-items-auto',
        'justify-items-start',
        'justify-items-end',
        'justify-items-center',
        'justify-items-stretch',
        'justify-self-auto',
        'justify-self-start',
        'justify-self-end',
        'justify-self-center',
        'justify-self-stretch',
        'content-start',
        'content-center',
        'content-end',
        'content-between',
        'content-around',
        'content-evenly',
        'items-stretch',
        'items-start',
        'items-center',
        'items-end',
        'items-baseline',
        'self-auto',
        'self-start',
        'self-end',
        'self-center',
        'self-stretch',
        'place-content-center',
        'place-content-start',
        'place-content-end',
        'place-content-between',
        'place-content-around',
        'place-content-evenly',
        'place-content-stretch',
        'place-items-auto',
        'place-items-start',
        'place-items-end',
        'place-items-center',
        'place-items-stretch',
        'place-self-auto',
        'place-self-start',
        'place-self-end',
        'place-self-center',
        'place-self-stretch',
        'w-0',
        'w-auto',
        'w-px',
        'w-full',
        'w-screen',
        'w-min',
        'w-max',
        'min-w-0',
        'min-w-full',
        'min-w-min',
        'min-w-max',
        'max-w-0',
        'max-w-none',
        'max-w-xs',
        'max-w-sm',
        'max-w-md',
        'max-w-lg',
        'max-w-xl',
        'max-w-full',
        'max-w-min',
        'max-w-max',
        'max-w-pose',
        'max-w-screen-sm',
        'max-w-screen-md',
        'max-w-screen-lg',
        'max-w-screen-xl',
        'h-0',
        'h-auto',
        'h-px',
        'h-full',
        'h-screen',
        'min-h-0',
        'min-h-full',
        'min-h-screen',
        'max-h-0',
        'max-h-px',
        'max-h-full',
        'max-h-screen',
        'bg-fixed',
        'bg-local',
        'bg-scroll',
        'bg-clip-border',
        'bg-clip-padding',
        'bg-clip-Content',
        'bg-clip-text',
        'bg-transparent',
        'bg-current',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-300',
        'bg-gray-400',
        'bg-gray-500',
        'bg-gray-600',
        'bg-gray-700',
        'bg-primary',
        'bg-primary-light',
        'bg-secondary',
        'bg-secondary2',
        'bg-info',
        'bg-info-light',
        'bg-success',
        'bg-success-light',
        'bg-danger',
        'bg-danger-light',
        'bg-warning',
        'bg-black',
        'bg-white',
        'bg-opacity-0',
        'bg-opacity-5',
        'bg-opacity-10',
        'bg-opacity-20',
        'bg-opacity-25',
        'bg-opacity-30',
        'bg-opacity-40',
        'bg-opacity-50',
        'bg-opacity-60',
        'bg-opacity-70',
        'bg-opacity-75',
        'bg-opacity-80',
        'bg-opacity-90',
        'bg-opacity-95',
        'bg-opacity-100',
        'bg-bottom',
        'bg-center',
        'bg-left',
        'bg-left-bottom',
        'bg-left-top',
        'bg-right',
        'bg-right-bottom',
        'bg-right-top',
        'bg-top',
        'bg-repeat',
        'bg-no-repeat',
        'bg-repeat-x',
        'bg-repeat-y',
        'bg-repeat-round',
        'bg-repeat-space',
        'bg-auto',
        'bg-cover',
        'bg-contain',
        'bg-none',
        'bg-gradient-to-t',
        'bg-gradient-to-tr',
        'bg-gradient-to-r',
        'bg-gradient-to-br',
        'bg-gradient-to-b',
        'bg-gradient-to-bl',
        'bg-gradient-to-l',
        'bg-gradient-to-tl',
        'transition',
        'transition-none',
        'transition-all',
        'transition-colors',
        'transition-opacity',
        'transition-shadow',
        'transition-transform',
        'animate-none',
        'animate-spin',
        'animate-ping',
        'animate-pulse',
        'animate-bounce',
        'appearance-none',
        'cursor-auto',
        'cursor-default',
        'cursor-pointer',
        'cursor-wait',
        'cursor-text',
        'cursor-move',
        'cursor-not-allowed',
        'outline-none',
        'outline-white',
        'outline-black',
        'pointerEventsNone',
        'pointerEventsAuto',
        'resize-none',
        'resize-y',
        'resize-x',
        'resize',
        'select-none',
        'select-text',
        'select-all',
        'select-auto',
        'sr-only',
        'not-sr-only',

        '{screensPrefix}:no-gutters',
        '{screensPrefix}:container',
        '{screensPrefix}:boxBorder',
        '{screensPrefix}:boxContent',
        '{screensPrefix}:hidden',
        '{screensPrefix}:block',
        '{screensPrefix}:inline-block',
        '{screensPrefix}:inline',
        '{screensPrefix}:inline-flex',
        '{screensPrefix}:table',
        '{screensPrefix}:table-caption',
        '{screensPrefix}:table-column',
        '{screensPrefix}:table-cell',
        '{screensPrefix}:table-column-group',
        '{screensPrefix}:table-footer-group',
        '{screensPrefix}:table-header-group',
        '{screensPrefix}:table-row-group',
        '{screensPrefix}:table-row',
        '{screensPrefix}:flow-root',
        '{screensPrefix}:grid',
        '{screensPrefix}:inline-grid',
        '{screensPrefix}:contents',
        '{screensPrefix}:float-right',
        '{screensPrefix}:float-left',
        '{screensPrefix}:float-none',
        '{screensPrefix}:clear-left',
        '{screensPrefix}:clear-right',
        '{screensPrefix}:clear-both',
        '{screensPrefix}:clear-none',
        '{screensPrefix}:object-contain',
        '{screensPrefix}:object-cover',
        '{screensPrefix}:object-fill',
        '{screensPrefix}:object-none',
        '{screensPrefix}:object-scale-down',
        '{screensPrefix}:object-bottom',
        '{screensPrefix}:object-center',
        '{screensPrefix}:object-left',
        '{screensPrefix}:object-left-bottom',
        '{screensPrefix}:object-left-top',
        '{screensPrefix}:object-right',
        '{screensPrefix}:object-right-bottom',
        '{screensPrefix}:object-right-top',
        '{screensPrefix}:object-top',
        '{screensPrefix}:overflow-auto',
        '{screensPrefix}:overflow-hidden',
        '{screensPrefix}:overflow-visible',
        '{screensPrefix}:overflow-scroll',
        '{screensPrefix}:overflow-x-auto',
        '{screensPrefix}:overflow-y-auto',
        '{screensPrefix}:overflow-x-hidden',
        '{screensPrefix}:overflow-y-hidden',
        '{screensPrefix}:overflow-x-visible',
        '{screensPrefix}:overflow-y-visible',
        '{screensPrefix}:overflow-x-scroll',
        '{screensPrefix}:overflow-y-scroll',
        '{screensPrefix}:overscroll-auto',
        '{screensPrefix}:overscroll-contain',
        '{screensPrefix}:overscroll-none',
        '{screensPrefix}:overscroll-y-auto',
        '{screensPrefix}:overscroll-y-contain',
        '{screensPrefix}:overscroll-y-none',
        '{screensPrefix}:overscroll-x-auto',
        '{screensPrefix}:overscroll-x-contain',
        '{screensPrefix}:overscroll-x-none',
        '{screensPrefix}:static',
        '{screensPrefix}:fixed',
        '{screensPrefix}:absolute',
        '{screensPrefix}:relative',
        '{screensPrefix}:sticky',
        '{screensPrefix}:visible',
        '{screensPrefix}:invisible',
        '{screensPrefix}:z-0',
        '{screensPrefix}:z-10',
        '{screensPrefix}:z-20',
        '{screensPrefix}:z-30',
        '{screensPrefix}:z-40',
        '{screensPrefix}:z-50',
        '{screensPrefix}:z-auto',
        '{screensPrefix}:grid-cols-1',
        '{screensPrefix}:grid-cols-2',
        '{screensPrefix}:grid-cols-3',
        '{screensPrefix}:grid-cols-4',
        '{screensPrefix}:grid-cols-5',
        '{screensPrefix}:grid-cols-6',
        '{screensPrefix}:grid-cols-7',
        '{screensPrefix}:grid-cols-8',
        '{screensPrefix}:grid-cols-9',
        '{screensPrefix}:grid-cols-10',
        '{screensPrefix}:grid-cols-11',
        '{screensPrefix}:grid-cols-12',
        '{screensPrefix}:grid-cols-none',
        '{screensPrefix}:col',
        '{screensPrefix}:col-auto',
        '{screensPrefix}:col-end-1',
        '{screensPrefix}:col-end-2',
        '{screensPrefix}:col-end-3',
        '{screensPrefix}:col-end-4',
        '{screensPrefix}:col-end-5',
        '{screensPrefix}:col-end-6',
        '{screensPrefix}:col-end-7',
        '{screensPrefix}:col-end-8',
        '{screensPrefix}:col-end-9',
        '{screensPrefix}:col-end-10',
        '{screensPrefix}:col-end-11',
        '{screensPrefix}:col-end-12',
        '{screensPrefix}:col-end-13',
        '{screensPrefix}:col-end-auto',
        '{screensPrefix}:col-span-1',
        '{screensPrefix}:col-span-2',
        '{screensPrefix}:col-span-3',
        '{screensPrefix}:col-span-4',
        '{screensPrefix}:col-span-5',
        '{screensPrefix}:col-span-6',
        '{screensPrefix}:col-span-7',
        '{screensPrefix}:col-span-8',
        '{screensPrefix}:col-span-9',
        '{screensPrefix}:col-span-10',
        '{screensPrefix}:col-span-11',
        '{screensPrefix}:col-span-12',
        '{screensPrefix}:col-span-full',
        '{screensPrefix}:col-start-1',
        '{screensPrefix}:col-start-2',
        '{screensPrefix}:col-start-3',
        '{screensPrefix}:col-start-4',
        '{screensPrefix}:col-start-5',
        '{screensPrefix}:col-start-6',
        '{screensPrefix}:col-start-7',
        '{screensPrefix}:col-start-8',
        '{screensPrefix}:col-start-9',
        '{screensPrefix}:col-start-10',
        '{screensPrefix}:col-start-11',
        '{screensPrefix}:col-start-12',
        '{screensPrefix}:col-start-13',
        '{screensPrefix}:col-start-auto',
        '{screensPrefix}:grid-rows-1',
        '{screensPrefix}:grid-rows-2',
        '{screensPrefix}:grid-rows-3',
        '{screensPrefix}:grid-rows-4',
        '{screensPrefix}:grid-rows-5',
        '{screensPrefix}:grid-rows-6',
        '{screensPrefix}:grid-rows-none',
        '{screensPrefix}:row',
        '{screensPrefix}:row-auto',
        '{screensPrefix}:row-span-1',
        '{screensPrefix}:row-span-2',
        '{screensPrefix}:row-span-3',
        '{screensPrefix}:row-span-4',
        '{screensPrefix}:row-span-5',
        '{screensPrefix}:row-span-6',
        '{screensPrefix}:row-span-full',
        '{screensPrefix}:row-start-1',
        '{screensPrefix}:row-start-2',
        '{screensPrefix}:row-start-3',
        '{screensPrefix}:row-start-4',
        '{screensPrefix}:row-start-5',
        '{screensPrefix}:row-start-6',
        '{screensPrefix}:row-start-7',
        '{screensPrefix}:row-start-auto',
        '{screensPrefix}:row-end-1',
        '{screensPrefix}:row-end-2',
        '{screensPrefix}:row-end-3',
        '{screensPrefix}:row-end-4',
        '{screensPrefix}:row-end-5',
        '{screensPrefix}:row-end-6',
        '{screensPrefix}:row-end-7',
        '{screensPrefix}:row-end-auto',
        '{screensPrefix}:grid-flow-row',
        '{screensPrefix}:grid-flow-col',
        '{screensPrefix}:grid-flow-row-dense',
        '{screensPrefix}:grid-flow-col-dense',
        '{screensPrefix}:auto-cols-auto',
        '{screensPrefix}:auto-cols-min',
        '{screensPrefix}:auto-cols-max',
        '{screensPrefix}:auto-cols-fr',
        '{screensPrefix}:auto-rows-auto',
        '{screensPrefix}:auto-rows-min',
        '{screensPrefix}:auto-rows-max',
        '{screensPrefix}:auto-rows-fr',
        '{screensPrefix}:m-auto',
        '{screensPrefix}:my-auto',
        '{screensPrefix}:mx-auto',
        '{screensPrefix}:mr-auto',
        '{screensPrefix}:ml-auto',
        '{screensPrefix}:text-d1',
        '{screensPrefix}:text-d2',
        '{screensPrefix}:text-d3',
        '{screensPrefix}:text-d4',
        '{screensPrefix}:text-d5',
        '{screensPrefix}:text-d6',
        '{screensPrefix}:text-d1',
        '{screensPrefix}:text-d2',
        '{screensPrefix}:text-d3',
        '{screensPrefix}:text-d4',
        '{screensPrefix}:text-d5',
        '{screensPrefix}:text-d6',
        '{screensPrefix}:text-d7',
        '{screensPrefix}:text-h1',
        '{screensPrefix}:text-h2',
        '{screensPrefix}:text-h3',
        '{screensPrefix}:text-h4',
        '{screensPrefix}:text-h5',
        '{screensPrefix}:text-h6',
        '{screensPrefix}:text-sBody',
        '{screensPrefix}:text-sTitle',
        '{screensPrefix}:text-h1',
        '{screensPrefix}:text-h2',
        '{screensPrefix}:text-h3',
        '{screensPrefix}:text-h4',
        '{screensPrefix}:text-h5',
        '{screensPrefix}:text-h6',
        '{screensPrefix}:text-transparent',
        '{screensPrefix}:text-current',
        '{screensPrefix}:text-black',
        '{screensPrefix}:text-white',
        '{screensPrefix}:text-info',
        '{screensPrefix}:text-danger',
        '{screensPrefix}:text-warning',
        '{screensPrefix}:text-success',
        '{screensPrefix}:text-primary',
        '{screensPrefix}:text-secondary',
        '{screensPrefix}:text-secondary2',
        '{screensPrefix}:text-gray-100',
        '{screensPrefix}:text-gray-200',
        '{screensPrefix}:text-gray-300',
        '{screensPrefix}:text-gray-400',
        '{screensPrefix}:text-gray-500',
        '{screensPrefix}:text-gray-600',
        '{screensPrefix}:text-gray-700',
        '{screensPrefix}:text-opacity-0',
        '{screensPrefix}:text-opacity-5',
        '{screensPrefix}:text-opacity-10',
        '{screensPrefix}:text-opacity-20',
        '{screensPrefix}:text-opacity-25',
        '{screensPrefix}:text-opacity-30',
        '{screensPrefix}:text-opacity-40',
        '{screensPrefix}:text-opacity-50',
        '{screensPrefix}:text-opacity-60',
        '{screensPrefix}:text-opacity-70',
        '{screensPrefix}:text-opacity-75',
        '{screensPrefix}:text-opacity-80',
        '{screensPrefix}:text-xs',
        '{screensPrefix}:text-sm',
        '{screensPrefix}:text-base',
        '{screensPrefix}:text-lg',
        '{screensPrefix}:text-xl',
        '{screensPrefix}:antialiased',
        '{screensPrefix}:subpixel-antialiased',
        '{screensPrefix}:italic',
        '{screensPrefix}:not-italic',
        '{screensPrefix}:font-thin',
        '{screensPrefix}:font-extralight',
        '{screensPrefix}:font-light',
        '{screensPrefix}:font-normal',
        '{screensPrefix}:font-medium',
        '{screensPrefix}:font-semibold',
        '{screensPrefix}:font-bold',
        '{screensPrefix}:font-extrabold',
        '{screensPrefix}:font-black',
        '{screensPrefix}:normal-nums',
        '{screensPrefix}:ordinal',
        '{screensPrefix}:slashed-zero',
        '{screensPrefix}:lining-nums',
        '{screensPrefix}:oldstyle-nums',
        '{screensPrefix}:proportional-nums',
        '{screensPrefix}:tabular-nums',
        '{screensPrefix}:diagonal-fractions',
        '{screensPrefix}:stack-fractions',
        '{screensPrefix}:tracking-tighter',
        '{screensPrefix}:tracking-tight',
        '{screensPrefix}:tracking-normal',
        '{screensPrefix}:tracking-wide',
        '{screensPrefix}:tracking-wider',
        '{screensPrefix}:tracking-widest',
        '{screensPrefix}:leading-none',
        '{screensPrefix}:leading-tight',
        '{screensPrefix}:leading-snug',
        '{screensPrefix}:leading-normal',
        '{screensPrefix}:leading-relaxed',
        '{screensPrefix}:leading-loose',
        '{screensPrefix}:leading-3',
        '{screensPrefix}:leading-4',
        '{screensPrefix}:leading-5',
        '{screensPrefix}:leading-6',
        '{screensPrefix}:leading-7',
        '{screensPrefix}:leading-8',
        '{screensPrefix}:leading-9',
        '{screensPrefix}:leading-10',
        '{screensPrefix}:list-none',
        '{screensPrefix}:list-disc',
        '{screensPrefix}:list-decimal',
        '{screensPrefix}:list-inside',
        '{screensPrefix}:list-outside',
        '{screensPrefix}:placeholder-transparent',
        '{screensPrefix}:placeholder-current',
        '{screensPrefix}:placeholder-black',
        '{screensPrefix}:placeholder-white',
        '{screensPrefix}:placeholder-primary',
        '{screensPrefix}:placeholder-info',
        '{screensPrefix}:placeholder-danger',
        '{screensPrefix}:placeholder-warning',
        '{screensPrefix}:placeholder-success',
        '{screensPrefix}:placeholder-gray-100',
        '{screensPrefix}:placeholder-gray-200',
        '{screensPrefix}:placeholder-gray-300',
        '{screensPrefix}:placeholder-gray-400',
        '{screensPrefix}:placeholder-gray-500',
        '{screensPrefix}:placeholder-gray-600',
        '{screensPrefix}:placeholder-gray-700',
        '{screensPrefix}:placeholder-opacity-0',
        '{screensPrefix}:placeholder-opacity-5',
        '{screensPrefix}:placeholder-opacity-10',
        '{screensPrefix}:placeholder-opacity-20',
        '{screensPrefix}:placeholder-opacity-25',
        '{screensPrefix}:placeholder-opacity-30',
        '{screensPrefix}:placeholder-opacity-40',
        '{screensPrefix}:placeholder-opacity-50',
        '{screensPrefix}:placeholder-opacity-60',
        '{screensPrefix}:placeholder-opacity-70',
        '{screensPrefix}:placeholder-opacity-75',
        '{screensPrefix}:placeholder-opacity-80',
        '{screensPrefix}:placeholder-opacity-90',
        '{screensPrefix}:placeholder-opacity-95',
        '{screensPrefix}:placeholder-opacity-100',
        '{screensPrefix}:text-left',
        '{screensPrefix}:text-center',
        '{screensPrefix}:text-right',
        '{screensPrefix}:text-justify',
        '{screensPrefix}:underline',
        '{screensPrefix}:line-through',
        '{screensPrefix}:no-underline',
        '{screensPrefix}:uppercase',
        '{screensPrefix}:lowercase',
        '{screensPrefix}:capitalize',
        '{screensPrefix}:normal-case',
        '{screensPrefix}:truncate',
        '{screensPrefix}:overflow-ellipsis',
        '{screensPrefix}:overflow-clip',
        '{screensPrefix}:align-baseline',
        '{screensPrefix}:align-top',
        '{screensPrefix}:align-middle',
        '{screensPrefix}:align-bottom',
        '{screensPrefix}:align-text-top',
        '{screensPrefix}:align-text-bottom',
        '{screensPrefix}:whitespace-normal',
        '{screensPrefix}:whitespace-nowrap',
        '{screensPrefix}:whitespace-pre',
        '{screensPrefix}:whitespace-pre-line',
        '{screensPrefix}:whitespace-pre-wrap',
        '{screensPrefix}:break-normal',
        '{screensPrefix}:break-words',
        '{screensPrefix}:break-all',
        '{screensPrefix}:keep-all',
        '{screensPrefix}:rounded-none',
        '{screensPrefix}:rounded-sm',
        '{screensPrefix}:rounded',
        '{screensPrefix}:rounded-md',
        '{screensPrefix}:rounded-lg',
        '{screensPrefix}:rounded-xl',
        '{screensPrefix}:rounded-2xl',
        '{screensPrefix}:rounded-3xl',
        '{screensPrefix}:rounded-full',
        '{screensPrefix}:rounded-t-none',
        '{screensPrefix}:rounded-r-none',
        '{screensPrefix}:rounded-b-none',
        '{screensPrefix}:rounded-l-none',
        '{screensPrefix}:rounded-t-sm',
        '{screensPrefix}:rounded-r-sm',
        '{screensPrefix}:rounded-b-sm',
        '{screensPrefix}:rounded-l-sm',
        '{screensPrefix}:rounded-t',
        '{screensPrefix}:rounded-r',
        '{screensPrefix}:rounded-b',
        '{screensPrefix}:rounded-l',
        '{screensPrefix}:rounded-t-md',
        '{screensPrefix}:rounded-r-md',
        '{screensPrefix}:rounded-b-md',
        '{screensPrefix}:rounded-l-md',
        '{screensPrefix}:rounded-t-lg',
        '{screensPrefix}:rounded-r-lg',
        '{screensPrefix}:rounded-b-lg',
        '{screensPrefix}:rounded-l-lg',
        '{screensPrefix}:rounded-t-xl',
        '{screensPrefix}:rounded-r-xl',
        '{screensPrefix}:rounded-b-xl',
        '{screensPrefix}:rounded-l-xl',
        '{screensPrefix}:rounded-t-2xl',
        '{screensPrefix}:rounded-r-2xl',
        '{screensPrefix}:rounded-b-2xl',
        '{screensPrefix}:rounded-l-2xl',
        '{screensPrefix}:rounded-t-3xl',
        '{screensPrefix}:rounded-r-3xl',
        '{screensPrefix}:rounded-b-3xl',
        '{screensPrefix}:rounded-l-3xl',
        '{screensPrefix}:rounded-t-full',
        '{screensPrefix}:rounded-r-full',
        '{screensPrefix}:rounded-b-full',
        '{screensPrefix}:rounded-l-full',
        '{screensPrefix}:rounded-tl-none',
        '{screensPrefix}:rounded-tr-none',
        '{screensPrefix}:rounded-br-none',
        '{screensPrefix}:rounded-bl-none',
        '{screensPrefix}:rounded-tl-sm',
        '{screensPrefix}:rounded-tr-sm',
        '{screensPrefix}:rounded-br-sm',
        '{screensPrefix}:rounded-bl-sm',
        '{screensPrefix}:rounded-tl',
        '{screensPrefix}:rounded-tr',
        '{screensPrefix}:rounded-br',
        '{screensPrefix}:rounded-bl',
        '{screensPrefix}:rounded-tl-md',
        '{screensPrefix}:rounded-tr-md',
        '{screensPrefix}:rounded-br-md',
        '{screensPrefix}:rounded-bl-md',
        '{screensPrefix}:rounded-tl-lg',
        '{screensPrefix}:rounded-tr-lg',
        '{screensPrefix}:rounded-br-lg',
        '{screensPrefix}:rounded-bl-lg',
        '{screensPrefix}:rounded-tl-xl',
        '{screensPrefix}:rounded-tr-xl',
        '{screensPrefix}:rounded-br-xl',
        '{screensPrefix}:rounded-bl-xl',
        '{screensPrefix}:rounded-tl-2xl',
        '{screensPrefix}:rounded-tr-2xl',
        '{screensPrefix}:rounded-br-2xl',
        '{screensPrefix}:rounded-bl-2xl',
        '{screensPrefix}:rounded-tl-3xl',
        '{screensPrefix}:rounded-tr-3xl',
        '{screensPrefix}:rounded-br-3xl',
        '{screensPrefix}:rounded-bl-3xl',
        '{screensPrefix}:rounded-tl-full',
        '{screensPrefix}:rounded-tr-full',
        '{screensPrefix}:rounded-br-full',
        '{screensPrefix}:rounded-bl-full',
        '{screensPrefix}:border',
        '{screensPrefix}:border0',
        '{screensPrefix}:border-1',
        '{screensPrefix}:border-2',
        '{screensPrefix}:border-3',
        '{screensPrefix}:border-4',
        '{screensPrefix}:border-8',
        '{screensPrefix}:border-t',
        '{screensPrefix}:border-t-0',
        '{screensPrefix}:border-t-1',
        '{screensPrefix}:border-t-2',
        '{screensPrefix}:border-t-3',
        '{screensPrefix}:border-t-4',
        '{screensPrefix}:border-t-8',
        '{screensPrefix}:border-r',
        '{screensPrefix}:border-r-0',
        '{screensPrefix}:border-r-1',
        '{screensPrefix}:border-r-2',
        '{screensPrefix}:border-r-3',
        '{screensPrefix}:border-r-4',
        '{screensPrefix}:border-r-8',
        '{screensPrefix}:border-b',
        '{screensPrefix}:border-b-0',
        '{screensPrefix}:border-b-1',
        '{screensPrefix}:border-b-2',
        '{screensPrefix}:border-b-3',
        '{screensPrefix}:border-b-4',
        '{screensPrefix}:border-b-8',
        '{screensPrefix}:border-l',
        '{screensPrefix}:border-l-0',
        '{screensPrefix}:border-l-1',
        '{screensPrefix}:border-l-2',
        '{screensPrefix}:border-l-3',
        '{screensPrefix}:border-l-4',
        '{screensPrefix}:border-l-8',
        '{screensPrefix}:border-transparent',
        '{screensPrefix}:border-current',
        '{screensPrefix}:border-black',
        '{screensPrefix}:border-white',
        '{screensPrefix}:border-primary',
        '{screensPrefix}:border-info',
        '{screensPrefix}:border-danger',
        '{screensPrefix}:border-warning',
        '{screensPrefix}:border-success',
        '{screensPrefix}:border-secondary2',
        '{screensPrefix}:border-gray-100',
        '{screensPrefix}:border-gray-200',
        '{screensPrefix}:border-gray-300',
        '{screensPrefix}:border-gray-400',
        '{screensPrefix}:border-gray-500',
        '{screensPrefix}:border-gray-600',
        '{screensPrefix}:border-gray-700',
        '{screensPrefix}:border-opacity-0',
        '{screensPrefix}:border-opacity-5',
        '{screensPrefix}:border-opacity-10',
        '{screensPrefix}:border-opacity-25',
        '{screensPrefix}:border-opacity-30',
        '{screensPrefix}:border-opacity-40',
        '{screensPrefix}:border-opacity-50',
        '{screensPrefix}:border-opacity-60',
        '{screensPrefix}:border-opacity-70',
        '{screensPrefix}:border-opacity-75',
        '{screensPrefix}:border-opacity-80',
        '{screensPrefix}:border-opacity-90',
        '{screensPrefix}:border-opacity-95',
        '{screensPrefix}:border-opacity-100',
        '{screensPrefix}:border-solid',
        '{screensPrefix}:border-dashed',
        '{screensPrefix}:border-dotted',
        '{screensPrefix}:border-double',
        '{screensPrefix}:border-none',
        '{screensPrefix}:ring-0',
        '{screensPrefix}:ring-1',
        '{screensPrefix}:ring-2',
        '{screensPrefix}:ring-4',
        '{screensPrefix}:ring-8',
        '{screensPrefix}:ring',
        '{screensPrefix}:ring-inset',
        '{screensPrefix}:ring-transparent',
        '{screensPrefix}:ring-current',
        '{screensPrefix}:ring-black',
        '{screensPrefix}:ring-white',
        '{screensPrefix}:ring-primary',
        '{screensPrefix}:ring-info',
        '{screensPrefix}:ring-danger',
        '{screensPrefix}:ring-warning',
        '{screensPrefix}:ring-success',
        '{screensPrefix}:ring-gray-100',
        '{screensPrefix}:ring-gray-200',
        '{screensPrefix}:ring-gray-300',
        '{screensPrefix}:ring-gray-400',
        '{screensPrefix}:ring-gray-500',
        '{screensPrefix}:ring-gray-600',
        '{screensPrefix}:ring-gray-700',
        '{screensPrefix}:ring-opacity-0',
        '{screensPrefix}:ring-opacity-5',
        '{screensPrefix}:ring-opacity-10',
        '{screensPrefix}:ring-opacity-20',
        '{screensPrefix}:ring-opacity-25',
        '{screensPrefix}:ring-opacity-30',
        '{screensPrefix}:ring-opacity-40',
        '{screensPrefix}:ring-opacity-50',
        '{screensPrefix}:ring-opacity-60',
        '{screensPrefix}:ring-opacity-70',
        '{screensPrefix}:ring-opacity-75',
        '{screensPrefix}:ring-opacity-80',
        '{screensPrefix}:ring-opacity-90',
        '{screensPrefix}:ring-opacity-95',
        '{screensPrefix}:ring-opacity-100',
        '{screensPrefix}:ring-offset-0',
        '{screensPrefix}:ring-offset-1',
        '{screensPrefix}:ring-offset-2',
        '{screensPrefix}:ring-offset-4',
        '{screensPrefix}:ring-offset-8',
        '{screensPrefix}:ring-offset-transparent',
        '{screensPrefix}:ring-offset-current',
        '{screensPrefix}:ring-offset-black',
        '{screensPrefix}:ring-offset-white',
        '{screensPrefix}:ring-offset-primary',
        '{screensPrefix}:ring-offset-info',
        '{screensPrefix}:ring-offset-danger',
        '{screensPrefix}:ring-offset-warning',
        '{screensPrefix}:ring-offset-success',
        '{screensPrefix}:ring-offset-gray-100',
        '{screensPrefix}:ring-offset-gray-200',
        '{screensPrefix}:ring-offset-gray-300',
        '{screensPrefix}:ring-offset-gray-400',
        '{screensPrefix}:ring-offset-gray-500',
        '{screensPrefix}:ring-offset-gray-600',
        '{screensPrefix}:ring-offset-gray-700',
        '{screensPrefix}:border-collapse',
        '{screensPrefix}:border-separate',
        '{screensPrefix}:table-auto',
        '{screensPrefix}:table-fixed',
        '{screensPrefix}:rotate-0',
        '{screensPrefix}:rotate-1',
        '{screensPrefix}:rotate-2',
        '{screensPrefix}:rotate-3',
        '{screensPrefix}:rotate-6',
        '{screensPrefix}:rotate-12',
        '{screensPrefix}:rotate-45',
        '{screensPrefix}:rotate-90',
        '{screensPrefix}:rotate-180',
        '{screensPrefix}:-rotate-180',
        '{screensPrefix}:-rotate-90',
        '{screensPrefix}:-rotate-45',
        '{screensPrefix}:-rotate-12',
        '{screensPrefix}:-rotate-6',
        '{screensPrefix}:-rotate-3',
        '{screensPrefix}:-rotate-2',
        '{screensPrefix}:-rotate-1',
        '{screensPrefix}:translate-x-0',
        '{screensPrefix}:translate-x-1/2',
        '{screensPrefix}:translate-x-full',
        '{screensPrefix}:-translate-x-1/2',
        '{screensPrefix}:-translate-x-full',
        '{screensPrefix}:translate-y-0',
        '{screensPrefix}:translate-y-1/2',
        '{screensPrefix}:translate-y-full',
        '{screensPrefix}:-translate-y-1/2',
        '{screensPrefix}:-translate-y-full',
        '{screensPrefix}:transform',
        '{screensPrefix}:transform-gpu',
        '{screensPrefix}:transform-none',
        '{screensPrefix}:shadow-sm',
        '{screensPrefix}:shadow',
        '{screensPrefix}:shadow-md',
        '{screensPrefix}:shadow-lg',
        '{screensPrefix}:shadow-xl',
        '{screensPrefix}:shadow-2xl',
        '{screensPrefix}:shadow-inner',
        '{screensPrefix}:shadow-none ',
        '{screensPrefix}:opacity-0',
        '{screensPrefix}:opacity-5',
        '{screensPrefix}:opacity-10',
        '{screensPrefix}:opacity-20',
        '{screensPrefix}:opacity-25',
        '{screensPrefix}:opacity-30',
        '{screensPrefix}:opacity-40',
        '{screensPrefix}:opacity-50',
        '{screensPrefix}:opacity-60',
        '{screensPrefix}:opacity-70',
        '{screensPrefix}:opacity-75',
        '{screensPrefix}:opacity-80',
        '{screensPrefix}:opacity-90',
        '{screensPrefix}:opacity-95',
        '{screensPrefix}:opacity-100',
        '{screensPrefix}:fill-current',
        '{screensPrefix}:stroke-current',
        '{screensPrefix}:stroke-0',
        '{screensPrefix}:stroke-1',
        '{screensPrefix}:stroke-2',
        '{screensPrefix}:flex',
        '{screensPrefix}:flex-row',
        '{screensPrefix}:flex-row-reverse',
        '{screensPrefix}:flex-col',
        '{screensPrefix}:flex-col-reverse',
        '{screensPrefix}:flex-wrap',
        '{screensPrefix}:flex-wrap-reverse',
        '{screensPrefix}:flex-nowrap',
        '{screensPrefix}:flex-1',
        '{screensPrefix}:flex-auto',
        '{screensPrefix}:flex-initial',
        '{screensPrefix}:flex-none',
        '{screensPrefix}:flex-grow',
        '{screensPrefix}:flex-grow-0',
        '{screensPrefix}:flex-shrink',
        '{screensPrefix}:flex-shrink-0',
        '{screensPrefix}:order-first',
        '{screensPrefix}:order-last',
        '{screensPrefix}:order-none',
        '{screensPrefix}:order-1',
        '{screensPrefix}:order-2',
        '{screensPrefix}:order-3',
        '{screensPrefix}:order-4',
        '{screensPrefix}:order-5',
        '{screensPrefix}:order-6',
        '{screensPrefix}:order-7',
        '{screensPrefix}:order-8',
        '{screensPrefix}:order-9',
        '{screensPrefix}:order-10',
        '{screensPrefix}:order-11',
        '{screensPrefix}:order-12',
        '{screensPrefix}:justify-start',
        '{screensPrefix}:justify-end',
        '{screensPrefix}:justify-center',
        '{screensPrefix}:justify-between',
        '{screensPrefix}:justify-around',
        '{screensPrefix}:justify-evenly',
        '{screensPrefix}:justify-items-auto',
        '{screensPrefix}:justify-items-start',
        '{screensPrefix}:justify-items-end',
        '{screensPrefix}:justify-items-center',
        '{screensPrefix}:justify-items-stretch',
        '{screensPrefix}:justify-self-auto',
        '{screensPrefix}:justify-self-start',
        '{screensPrefix}:justify-self-end',
        '{screensPrefix}:justify-self-center',
        '{screensPrefix}:justify-self-stretch',
        '{screensPrefix}:content-start',
        '{screensPrefix}:content-center',
        '{screensPrefix}:content-end',
        '{screensPrefix}:content-between',
        '{screensPrefix}:content-around',
        '{screensPrefix}:content-evenly',
        '{screensPrefix}:items-stretch',
        '{screensPrefix}:items-start',
        '{screensPrefix}:items-center',
        '{screensPrefix}:items-end',
        '{screensPrefix}:items-baseline',
        '{screensPrefix}:self-auto',
        '{screensPrefix}:self-start',
        '{screensPrefix}:self-end',
        '{screensPrefix}:self-center',
        '{screensPrefix}:self-stretch',
        '{screensPrefix}:place-content-center',
        '{screensPrefix}:place-content-start',
        '{screensPrefix}:place-content-end',
        '{screensPrefix}:place-content-between',
        '{screensPrefix}:place-content-around',
        '{screensPrefix}:place-content-evenly',
        '{screensPrefix}:place-content-stretch',
        '{screensPrefix}:place-items-auto',
        '{screensPrefix}:place-items-start',
        '{screensPrefix}:place-items-end',
        '{screensPrefix}:place-items-center',
        '{screensPrefix}:place-items-stretch',
        '{screensPrefix}:place-self-auto',
        '{screensPrefix}:place-self-start',
        '{screensPrefix}:place-self-end',
        '{screensPrefix}:place-self-center',
        '{screensPrefix}:place-self-stretch',
        '{screensPrefix}:w-0',
        '{screensPrefix}:w-auto',
        '{screensPrefix}:w-px',
        '{screensPrefix}:w-full',
        '{screensPrefix}:w-screen',
        '{screensPrefix}:w-min',
        '{screensPrefix}:w-max',
        '{screensPrefix}:min-w-0',
        '{screensPrefix}:min-w-full',
        '{screensPrefix}:min-w-min',
        '{screensPrefix}:min-w-max',
        '{screensPrefix}:max-w-0',
        '{screensPrefix}:max-w-none',
        '{screensPrefix}:max-w-xs',
        '{screensPrefix}:max-w-sm',
        '{screensPrefix}:max-w-md',
        '{screensPrefix}:max-w-lg',
        '{screensPrefix}:max-w-xl',
        '{screensPrefix}:max-w-full',
        '{screensPrefix}:max-w-min',
        '{screensPrefix}:max-w-max',
        '{screensPrefix}:max-w-pose',
        '{screensPrefix}:max-w-screen-sm',
        '{screensPrefix}:max-w-screen-md',
        '{screensPrefix}:max-w-screen-lg',
        '{screensPrefix}:max-w-screen-xl',
        '{screensPrefix}:h-0',
        '{screensPrefix}:h-auto',
        '{screensPrefix}:h-px',
        '{screensPrefix}:h-full',
        '{screensPrefix}:h-screen',
        '{screensPrefix}:min-h-0',
        '{screensPrefix}:min-h-full',
        '{screensPrefix}:min-h-screen',
        '{screensPrefix}:max-h-0',
        '{screensPrefix}:max-h-px',
        '{screensPrefix}:max-h-full',
        '{screensPrefix}:max-h-screen',
        '{screensPrefix}:bg-fixed',
        '{screensPrefix}:bg-local',
        '{screensPrefix}:bg-scroll',
        '{screensPrefix}:bg-clip-border',
        '{screensPrefix}:bg-clip-padding',
        '{screensPrefix}:bg-clip-Content',
        '{screensPrefix}:bg-clip-text',
        '{screensPrefix}:bg-transparent',
        '{screensPrefix}:bg-current',
        '{screensPrefix}:bg-gray-100',
        '{screensPrefix}:bg-gray-200',
        '{screensPrefix}:bg-gray-300',
        '{screensPrefix}:bg-gray-400',
        '{screensPrefix}:bg-gray-500',
        '{screensPrefix}:bg-gray-600',
        '{screensPrefix}:bg-gray-700',
        '{screensPrefix}:bg-primary',
        '{screensPrefix}:bg-primary-light',
        '{screensPrefix}:bg-secondary',
        '{screensPrefix}:bg-secondary2',
        '{screensPrefix}:bg-info',
        '{screensPrefix}:bg-info-light',
        '{screensPrefix}:bg-success',
        '{screensPrefix}:bg-success-light',
        '{screensPrefix}:bg-danger',
        '{screensPrefix}:bg-danger-light',
        '{screensPrefix}:bg-warning',
        '{screensPrefix}:bg-black',
        '{screensPrefix}:bg-white',
        '{screensPrefix}:bg-opacity-0',
        '{screensPrefix}:bg-opacity-5',
        '{screensPrefix}:bg-opacity-10',
        '{screensPrefix}:bg-opacity-20',
        '{screensPrefix}:bg-opacity-25',
        '{screensPrefix}:bg-opacity-30',
        '{screensPrefix}:bg-opacity-40',
        '{screensPrefix}:bg-opacity-50',
        '{screensPrefix}:bg-opacity-60',
        '{screensPrefix}:bg-opacity-70',
        '{screensPrefix}:bg-opacity-75',
        '{screensPrefix}:bg-opacity-80',
        '{screensPrefix}:bg-opacity-90',
        '{screensPrefix}:bg-opacity-95',
        '{screensPrefix}:bg-opacity-100',
        '{screensPrefix}:bg-bottom',
        '{screensPrefix}:bg-center',
        '{screensPrefix}:bg-left',
        '{screensPrefix}:bg-left-bottom',
        '{screensPrefix}:bg-left-top',
        '{screensPrefix}:bg-right',
        '{screensPrefix}:bg-right-bottom',
        '{screensPrefix}:bg-right-top',
        '{screensPrefix}:bg-top',
        '{screensPrefix}:bg-repeat',
        '{screensPrefix}:bg-no-repeat',
        '{screensPrefix}:bg-repeat-x',
        '{screensPrefix}:bg-repeat-y',
        '{screensPrefix}:bg-repeat-round',
        '{screensPrefix}:bg-repeat-space',
        '{screensPrefix}:bg-auto',
        '{screensPrefix}:bg-cover',
        '{screensPrefix}:bg-contain',
        '{screensPrefix}:bg-none',
        '{screensPrefix}:bg-gradient-to-t',
        '{screensPrefix}:bg-gradient-to-tr',
        '{screensPrefix}:bg-gradient-to-r',
        '{screensPrefix}:bg-gradient-to-br',
        '{screensPrefix}:bg-gradient-to-b',
        '{screensPrefix}:bg-gradient-to-bl',
        '{screensPrefix}:bg-gradient-to-l',
        '{screensPrefix}:bg-gradient-to-tl',
        '{screensPrefix}:transition',
        '{screensPrefix}:transition-none',
        '{screensPrefix}:transition-all',
        '{screensPrefix}:transition-colors',
        '{screensPrefix}:transition-opacity',
        '{screensPrefix}:transition-shadow',
        '{screensPrefix}:transition-transform',
        '{screensPrefix}:animate-none',
        '{screensPrefix}:animate-spin',
        '{screensPrefix}:animate-ping',
        '{screensPrefix}:animate-pulse',
        '{screensPrefix}:animate-bounce',
        '{screensPrefix}:appearance-none',
        '{screensPrefix}:cursor-auto',
        '{screensPrefix}:cursor-default',
        '{screensPrefix}:cursor-pointer',
        '{screensPrefix}:cursor-wait',
        '{screensPrefix}:cursor-text',
        '{screensPrefix}:cursor-move',
        '{screensPrefix}:cursor-not-allowed',
        '{screensPrefix}:outline-none',
        '{screensPrefix}:outline-white',
        '{screensPrefix}:outline-black',
        '{screensPrefix}:pointerEventsNone',
        '{screensPrefix}:pointerEventsAuto',
        '{screensPrefix}:resize-none',
        '{screensPrefix}:resize-y',
        '{screensPrefix}:resize-x',
        '{screensPrefix}:resize',
        '{screensPrefix}:select-none',
        '{screensPrefix}:select-text',
        '{screensPrefix}:select-all',
        '{screensPrefix}:select-auto',
        '{screensPrefix}:sr-only',
        '{screensPrefix}:not-sr-only',
      ],
    }),
    plugin(function ({ addUtilities }) {
      const newUtilities = {
        '.no-scrol:lbar::-webkit-scrollbar': {
          display: 'none',
        },
        '.no-scrol:lbar': {
          scrollbarWidth: 'none',
          msOverflowStyle: 'none',
        },
        '.lift': {
          transition: 'box-shadow .25s ease, transform .25s ease !important',
        },
        '.skew-10d:eg': {
          transform: 'skewY(-10deg)',
        },
        '.skew-15d:eg': {
          transform: 'skewY(-15deg)',
        },
        '.btn-xs': {
          padding: '8px 12px',
          borderRadius: '5px',
          fontSize: '14px',
        },
        '.btn-sm': {
          padding: '8px 20px',
          borderRadius: '5px',
          maxHeight: '38px',
          fontSize: '14px',
        },
        '.btn-md': {
          padding: '10px 10px',
          borderRadius: '5px',
          maxHeight: '42px',
          minWidth: '150px',
          fontSize: '14px',
        },
        'btn-lg-tab': {
          minWidth: '170px',
        },
        '.btn-lg': {
          padding: '18px 0px',
          minWidth: '300px',
          borderRadius: '5px',
          maxHeight: '56px',
          fontSize: '14px',
        },
        '.btn-primary': {
          backgroundColor:
            process.env.CONF_IS_TEENS == 'true' ? '#4c9cff' : '#7a5de8',
          color: colors.white,
        },
        '.btn-outlined': {
          border: '1px solid',
          background: '#fff',
          color: process.env.CONF_IS_TEENS == 'true' ? '#4c9cff' : '#7a5de8',
        },
        '.btn-disabled': {
          backgroundColor: '#e2e9f2',
          color: colors.white,
        },
        '.chip-md': {
          padding: '7px 12px',
          borderRadius: '9999px',
        },
        '.chip-sm': {
          fontSize: '12px',
          padding: '2px 12px',
          borderRadius: '9999px',
        },
        '.flex-basis-0': {
          flexBasis: 0,
        },

        // col, row
        '.row': {
          display: 'flex',
          flexWrap: 'wrap',
        },

        '.no-gutters': {
          marginRight: 0,
          marginLeft: 0,
        },

        '.col': {
          position: 'relative',
          // width: '100%',
          // flexBasis: 0,
          flexGrow: 1,
          maxWidth: '100%',
        },
        // '.col-1': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 8.33333%',
        //   maxWidth: '8.33333%',
        // },
        // '.col-2': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 16.66667%',
        //   maxWidth: '16.66667%',
        // },
        // '.col-3': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 25%',
        //   maxWidth: '25%',
        // },
        // '.col-4': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 33.33333%',
        //   maxWidth: '33.33333%',
        // },
        // '.col-5': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 41.66667%',
        //   maxWidth: '41.66667%',
        // },
        // '.col-6': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 50%',
        //   maxWidth: '50%',
        // },
        // '.col-7': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 58.33333%',
        //   maxWidth: '58.33333%',
        // },
        // '.col-8': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 66.66667%',
        //   maxWidth: '66.66667%',
        // },
        // '.col-9': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 75%',
        //   maxWidth: '75%',
        // },
        // '.col-10': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 83.33333%',
        //   maxWidth: '83.33333%',
        // },
        // '.col-11': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 91.66667%',
        //   maxWidth: '91.66667%',
        // },
        // '.col-12': {
        //   position: 'relative',
        //   width: '100%',
        //   flex: '0 0 100%',
        //   maxWidth: '100%',
        // },
        '.col-auto': {
          position: 'relative',
          flex: '0 0 auto',
          width: 'auto',
          maxWidth: '100%',
        },

        // '.offset-1': {
        //   marginLeft: '8.33333%',
        // },

        // '.offset-2': {
        //   marginLeft: '16.66667%',
        // },

        // '.offset-3': {
        //   marginLeft: '25%',
        // },

        // '.offset-4': {
        //   marginLeft: '33.33333%',
        // },

        // '.offset-5': {
        //   marginLeft: '41.66667%',
        // },

        // '.offset-6': {
        //   marginLeft: '50%',
        // },

        // '.offset-7': {
        //   marginLeft: '58.33333%',
        // },

        // '.offset-8': {
        //   marginLeft: '66.66667%',
        // },

        // '.offset-9': {
        //   marginLeft: '75%',
        // },

        // '.offset-10': {
        //   marginLeft: ' 83.33333%',
        // },

        // '.offset-11': {
        //   marginLeft: '91.66667%',
        // },
      }

      addUtilities(newUtilities)
    }),
  ],
  corePlugins: {
    container: false,
    ringColor: false,
  },
}
