/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import React from "react";

const BasicHead = () => {
	return (
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default BasicHead;
